services:
  nginx:
    image: nginx:1.27.5-alpine
    container_name: dronekit_nginx
    expose:
      - "80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/var/www/intodelivery-backend/static
      - ./media:/var/www/intodelivery-backend/media
    networks:
      - dronekit_network
    depends_on:
      - web
    restart: always

  web:
    build:
      context: .
      dockerfile: app/Docker/prod/Dockerfile
    container_name: dronekit_fastapi
    restart: always
    networks:
      - dronekit_network

networks:
  dronekit_network:
    name: dronekit_network
    driver: bridge
